/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author BaoLong
 */
public class viewQuanLyThucUong extends javax.swing.JFrame {

    /**
     * Creates new form formQuanLyBan
     */
    public viewQuanLyThucUong() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn = new javax.swing.JPanel();
        pn1 = new javax.swing.JPanel();
        toolBar = new javax.swing.JToolBar();
        btThemThucUong = new javax.swing.JButton();
        btSuaThucUong = new javax.swing.JButton();
        btXoaThucUong = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        pn2 = new javax.swing.JPanel();
        pn21 = new javax.swing.JPanel();
        splitPane = new javax.swing.JSplitPane();
        pnDanhSach = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        listDanhSach = new javax.swing.JList<>();
        pnChucNang = new javax.swing.JPanel();
        btDSBan = new javax.swing.JButton();
        btDSKhuVuc = new javax.swing.JButton();
        pn22 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CafeManagement_Quản Lý Thức Uống");

        pn1.setBackground(new java.awt.Color(204, 204, 255));

        toolBar.setBackground(new java.awt.Color(153, 153, 255));
        toolBar.setFloatable(false);
        toolBar.setRollover(true);

        btThemThucUong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1488801680_Plus__Orange.png"))); // NOI18N
        btThemThucUong.setText("Thêm Thức Uống");
        btThemThucUong.setFocusable(false);
        btThemThucUong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btThemThucUong);

        btSuaThucUong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1488802703_edit.png"))); // NOI18N
        btSuaThucUong.setText("Sửa Thức uống");
        btSuaThucUong.setFocusable(false);
        btSuaThucUong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btSuaThucUong);

        btXoaThucUong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1488802717_DeleteRed.png"))); // NOI18N
        btXoaThucUong.setText("Xóa Thức Uống");
        btXoaThucUong.setFocusable(false);
        btXoaThucUong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btXoaThucUong);

        btReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1489070944_refresh.png"))); // NOI18N
        btReset.setText("Reset");
        btReset.setFocusable(false);
        btReset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btReset);

        javax.swing.GroupLayout pn1Layout = new javax.swing.GroupLayout(pn1);
        pn1.setLayout(pn1Layout);
        pn1Layout.setHorizontalGroup(
            pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn1Layout.setVerticalGroup(
            pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pn21.setBackground(new java.awt.Color(204, 204, 255));

        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        pnDanhSach.setBackground(new java.awt.Color(204, 204, 255));
        pnDanhSach.setPreferredSize(new java.awt.Dimension(254, 200));

        listDanhSach.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listDanhSach.setPreferredSize(new java.awt.Dimension(33, 150));
        scrollPane.setViewportView(listDanhSach);

        javax.swing.GroupLayout pnDanhSachLayout = new javax.swing.GroupLayout(pnDanhSach);
        pnDanhSach.setLayout(pnDanhSachLayout);
        pnDanhSachLayout.setHorizontalGroup(
            pnDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
        );
        pnDanhSachLayout.setVerticalGroup(
            pnDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
        );

        splitPane.setTopComponent(pnDanhSach);

        pnChucNang.setBackground(new java.awt.Color(204, 204, 255));

        btDSBan.setBackground(new java.awt.Color(153, 153, 255));
        btDSBan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btDSBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1488817435_list-alt.png"))); // NOI18N
        btDSBan.setText("Danh Sách Thức Uống");
        btDSBan.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        btDSKhuVuc.setBackground(new java.awt.Color(153, 153, 255));
        btDSKhuVuc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btDSKhuVuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1488817435_list-alt.png"))); // NOI18N
        btDSKhuVuc.setText("Danh Sách Loại Thức Uống");
        btDSKhuVuc.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout pnChucNangLayout = new javax.swing.GroupLayout(pnChucNang);
        pnChucNang.setLayout(pnChucNangLayout);
        pnChucNangLayout.setHorizontalGroup(
            pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btDSBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btDSKhuVuc, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
        );
        pnChucNangLayout.setVerticalGroup(
            pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChucNangLayout.createSequentialGroup()
                .addComponent(btDSBan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btDSKhuVuc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 435, Short.MAX_VALUE))
        );

        splitPane.setRightComponent(pnChucNang);

        javax.swing.GroupLayout pn21Layout = new javax.swing.GroupLayout(pn21);
        pn21.setLayout(pn21Layout);
        pn21Layout.setHorizontalGroup(
            pn21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn21Layout.createSequentialGroup()
                .addComponent(splitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn21Layout.setVerticalGroup(
            pn21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pn22.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout pn22Layout = new javax.swing.GroupLayout(pn22);
        pn22.setLayout(pn22Layout);
        pn22Layout.setHorizontalGroup(
            pn22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
        );
        pn22Layout.setVerticalGroup(
            pn22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pn2Layout = new javax.swing.GroupLayout(pn2);
        pn2.setLayout(pn2Layout);
        pn2Layout.setHorizontalGroup(
            pn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn2Layout.createSequentialGroup()
                .addComponent(pn21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn2Layout.setVerticalGroup(
            pn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnLayout = new javax.swing.GroupLayout(pn);
        pn.setLayout(pnLayout);
        pnLayout.setHorizontalGroup(
            pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnLayout.setVerticalGroup(
            pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLayout.createSequentialGroup()
                .addComponent(pn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewQuanLyThucUong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewQuanLyThucUong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewQuanLyThucUong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewQuanLyThucUong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewQuanLyThucUong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDSBan;
    private javax.swing.JButton btDSKhuVuc;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btSuaThucUong;
    private javax.swing.JButton btThemThucUong;
    private javax.swing.JButton btXoaThucUong;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JList<String> listDanhSach;
    private javax.swing.JPanel pn;
    private javax.swing.JPanel pn1;
    private javax.swing.JPanel pn2;
    private javax.swing.JPanel pn21;
    private javax.swing.JPanel pn22;
    private javax.swing.JPanel pnChucNang;
    private javax.swing.JPanel pnDanhSach;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables
}
