/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author BaoLong
 */
public class viewGiaoDich extends javax.swing.JFrame {

    /**
     * Creates new form formGiaoDich
     */
    public viewGiaoDich() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn = new javax.swing.JPanel();
        tabPn = new javax.swing.JTabbedPane();
        pnDanhMuc = new javax.swing.JPanel();
        btGiaoDich = new javax.swing.JButton();
        btBan = new javax.swing.JButton();
        btThucDon = new javax.swing.JButton();
        btNhanVien = new javax.swing.JButton();
        btKhoHang2 = new javax.swing.JButton();
        pnThongKe = new javax.swing.JPanel();
        pnQuanLy = new javax.swing.JPanel();
        pn2 = new javax.swing.JPanel();
        btThanhToan = new javax.swing.JPanel();
        btNhanKhach = new javax.swing.JButton();
        btGoiMon = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lbMaBan = new javax.swing.JLabel();
        lbNgayLapPhieu = new javax.swing.JLabel();
        lbTongTien = new javax.swing.JLabel();
        tfNgayLapPhieu = new javax.swing.JTextField();
        tfTongTien = new javax.swing.JTextField();
        tfNgayLapPhieu1 = new javax.swing.JTextField();
        pnHoaDon = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CafeManagement_Giao Dịch");

        pn.setBackground(new java.awt.Color(204, 204, 255));

        pnDanhMuc.setBackground(new java.awt.Color(153, 153, 255));

        btGiaoDich.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btGiaoDich.setForeground(new java.awt.Color(102, 102, 255));
        btGiaoDich.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1488792929_go-home.png"))); // NOI18N
        btGiaoDich.setText("   Giao Dịch");

        btBan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btBan.setForeground(new java.awt.Color(102, 102, 255));
        btBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1488793219_house_kitchen_table.png"))); // NOI18N
        btBan.setText("   Bàn - Dãy Bàn ");

        btThucDon.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btThucDon.setForeground(new java.awt.Color(102, 102, 255));
        btThucDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1488793436_wine.png"))); // NOI18N
        btThucDon.setText("   Thực Đơn");

        btNhanVien.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btNhanVien.setForeground(new java.awt.Color(102, 102, 255));
        btNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1488793561_Login Manager.png"))); // NOI18N
        btNhanVien.setText("   Nhân Viên");

        btKhoHang2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btKhoHang2.setForeground(new java.awt.Color(102, 102, 255));
        btKhoHang2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1488793938_package-x-generic.png"))); // NOI18N
        btKhoHang2.setText("  Kho Hàng");

        javax.swing.GroupLayout pnDanhMucLayout = new javax.swing.GroupLayout(pnDanhMuc);
        pnDanhMuc.setLayout(pnDanhMucLayout);
        pnDanhMucLayout.setHorizontalGroup(
            pnDanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDanhMucLayout.createSequentialGroup()
                .addComponent(btGiaoDich, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btThucDon, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btKhoHang2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnDanhMucLayout.setVerticalGroup(
            pnDanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btGiaoDich, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btBan, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
            .addComponent(btThucDon, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
            .addComponent(btNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
            .addComponent(btKhoHang2, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
        );

        tabPn.addTab("Danh mục", pnDanhMuc);

        javax.swing.GroupLayout pnThongKeLayout = new javax.swing.GroupLayout(pnThongKe);
        pnThongKe.setLayout(pnThongKeLayout);
        pnThongKeLayout.setHorizontalGroup(
            pnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1135, Short.MAX_VALUE)
        );
        pnThongKeLayout.setVerticalGroup(
            pnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
        );

        tabPn.addTab("Thống kê", pnThongKe);

        pnQuanLy.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnQuanLyLayout = new javax.swing.GroupLayout(pnQuanLy);
        pnQuanLy.setLayout(pnQuanLyLayout);
        pnQuanLyLayout.setHorizontalGroup(
            pnQuanLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnQuanLyLayout.setVerticalGroup(
            pnQuanLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        btThanhToan.setBackground(new java.awt.Color(153, 153, 255));

        btNhanKhach.setBackground(new java.awt.Color(204, 204, 255));
        btNhanKhach.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btNhanKhach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1488798814_customers.png"))); // NOI18N
        btNhanKhach.setText("Nhận Khách");

        btGoiMon.setBackground(new java.awt.Color(204, 204, 255));
        btGoiMon.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btGoiMon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1488799092_order.png"))); // NOI18N
        btGoiMon.setText(" Gọi Món");

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1488799283_document-02.png"))); // NOI18N
        jButton3.setText("Thanh Toán");

        lbMaBan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbMaBan.setText("Mã Bàn");

        lbNgayLapPhieu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNgayLapPhieu.setText("Ngày Lập Phiếu");

        lbTongTien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTongTien.setText("Tổng Tiền");

        tfNgayLapPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNgayLapPhieuActionPerformed(evt);
            }
        });

        tfTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTongTienActionPerformed(evt);
            }
        });

        tfNgayLapPhieu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNgayLapPhieu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btThanhToanLayout = new javax.swing.GroupLayout(btThanhToan);
        btThanhToan.setLayout(btThanhToanLayout);
        btThanhToanLayout.setHorizontalGroup(
            btThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btThanhToanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btThanhToanLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btNhanKhach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btGoiMon, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(btThanhToanLayout.createSequentialGroup()
                        .addGroup(btThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbMaBan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbNgayLapPhieu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(lbTongTien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(btThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(btThanhToanLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(btThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                                    .addComponent(tfNgayLapPhieu1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btThanhToanLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(tfNgayLapPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        btThanhToanLayout.setVerticalGroup(
            btThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btThanhToanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNhanKhach)
                    .addComponent(btGoiMon)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(btThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaBan)
                    .addComponent(tfNgayLapPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(btThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNgayLapPhieu)
                    .addComponent(tfNgayLapPhieu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(btThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTongTien)
                    .addComponent(tfTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout pnHoaDonLayout = new javax.swing.GroupLayout(pnHoaDon);
        pnHoaDon.setLayout(pnHoaDonLayout);
        pnHoaDonLayout.setHorizontalGroup(
            pnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnHoaDonLayout.setVerticalGroup(
            pnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pn2Layout = new javax.swing.GroupLayout(pn2);
        pn2.setLayout(pn2Layout);
        pn2Layout.setHorizontalGroup(
            pn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn2Layout.setVerticalGroup(
            pn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnLayout = new javax.swing.GroupLayout(pn);
        pn.setLayout(pnLayout);
        pnLayout.setHorizontalGroup(
            pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPn)
            .addComponent(pnQuanLy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnLayout.setVerticalGroup(
            pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLayout.createSequentialGroup()
                .addComponent(tabPn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNgayLapPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNgayLapPhieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNgayLapPhieuActionPerformed

    private void tfTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTongTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTongTienActionPerformed

    private void tfNgayLapPhieu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNgayLapPhieu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNgayLapPhieu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewGiaoDich.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewGiaoDich.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewGiaoDich.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewGiaoDich.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewGiaoDich().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBan;
    private javax.swing.JButton btGiaoDich;
    private javax.swing.JButton btGoiMon;
    private javax.swing.JButton btKhoHang2;
    private javax.swing.JButton btNhanKhach;
    private javax.swing.JButton btNhanVien;
    private javax.swing.JPanel btThanhToan;
    private javax.swing.JButton btThucDon;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbMaBan;
    private javax.swing.JLabel lbNgayLapPhieu;
    private javax.swing.JLabel lbTongTien;
    private javax.swing.JPanel pn;
    private javax.swing.JPanel pn2;
    private javax.swing.JPanel pnDanhMuc;
    private javax.swing.JPanel pnHoaDon;
    private javax.swing.JPanel pnQuanLy;
    private javax.swing.JPanel pnThongKe;
    private javax.swing.JTabbedPane tabPn;
    private javax.swing.JTextField tfNgayLapPhieu;
    private javax.swing.JTextField tfNgayLapPhieu1;
    private javax.swing.JTextField tfTongTien;
    // End of variables declaration//GEN-END:variables
}
